rootProject.name = "fcfs-coupon"
include("fcfs-coupon-api-fcfs")
include("fcfs-coupon-api-coupon")
include("fcfs-coupon-api-coupon-dto")
include("fcfs-coupon-domain-fcfs")
include("fcfs-coupon-domain-coupon")
include("fcfs-coupon-domain-history")
include("fcfs-coupon-common")
include("fcfs-coupon-mq")
include("fcfs-coupon-client-coupon")
include("fcfs-coupon-log")
